@baseUrl = http://127.0.0.1:8000

### Recupera tutti i progetti
GET {{baseUrl}}/projects/get_all_projects

### Recupera i progetti filtrati per area
GET {{baseUrl}}/projects/get_projects_by_area?area_id=1

### Recupera un progetto
GET {{baseUrl}}/projects/get_project?project_id=1

### Inserisce un nuovo progetto
POST {{baseUrl}}/projects/insert_project
Content-Type: application/json

{
  "area_id": 1,
  "name": "Nuovo progetto da test",
  "description": "Descrizione progetto da test"
}

### Aggiorna un progetto
POST {{baseUrl}}/projects/update_project
Content-Type: application/json

{
  "project_id": 1,
  "name": "Progetto aggiornato da test",
  "description": "Descrizione aggiornata da test"
}

### Elimina un progetto
POST {{baseUrl}}/projects/delete_project
Content-Type: application/json

{
  "project_id": 1
}
