CREATE TABLE areas(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL
);

CREATE TABLE projects (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    description TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tasks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id INTEGER NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    completed INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE calendar(
    id INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE settings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    theme TEXT NOT NULL DEFAULT 'system',
    custom_background TEXT NOT NULL DEFAULT '#0f172a',
    custom_foreground TEXT NOT NULL DEFAULT '#f0f9ff',
    custom_card TEXT NOT NULL DEFAULT '#1e3a8a',
    custom_border TEXT NOT NULL DEFAULT '#3b82f6',
    custom_hover TEXT NOT NULL DEFAULT '#2563eb',
    custom_hover_text TEXT NOT NULL DEFAULT '#f0f9ff'
);